In [1]:
import numpy as np
import math
import itertools

In [2]:
def game(n):
    # Implementing the game, taking n as input
    Mat = np.ones(n**2)*2 # choose two to be arbitrary
    Mat = Mat.reshape(n,n)
    turn = input('Which player goes first? Please type 0 or 1: ')
    for i in range(n**2):
        print("Player", turn, "please enter: ")
        row = int(input('row = '))
        col = int(input('column = '))       
        if Mat[row][col] == 2:
            Mat[row][col] = turn
        else:
            print("Invalid entries, please try again.")
            return 0
        if turn == 1:
            turn = 0
        else: 
            turn = 1
        print(Mat)
    print("The determinant of the resultant matrix is:")
    return np.linalg.det(Mat)

In [3]:
game(2)

Which player goes first? Please type 0 or 1: 0
Player 0 please enter: 
row = 1
column = 1
[[2. 2.]
 [2. 0.]]
Player 1 please enter: 
row = 0
column = 1
[[2. 1.]
 [2. 0.]]
Player 0 please enter: 
row = 1
column = 0
[[2. 1.]
 [0. 0.]]
Player 1 please enter: 
row = 0
column = 0
[[1. 1.]
 [0. 0.]]
The determinant of the resultant matrix is:


0.0

In [4]:
def game_even(n):
    # returns the number of non-zero determinant matrices
    # for n is even
    count = 0 # Counter for the number of non-zero det matrices
    for comb in itertools.combinations(np.arange(n**2), int(n**2/2)):
        mat = np.array([0]*(n**2))
        for k in comb:
            mat[k] = 1
        mat = mat.reshape(n,n)
        if np.linalg.det(mat) != 0:
            count += 1
            # print(mat)
    # print("The number of non-zero determinant matrices is:") 
    return count
        

In [5]:
def prob(count, n):
    return count / (math.comb(n**2, int((n**2)/2)))

In [6]:
game_even(2)

2

In [7]:
game_even(4)

5328

In [8]:
prob(game_even(2), 2)

0.3333333333333333

In [9]:
prob(game_even(4), 4)

0.413986013986014

In [10]:
# n = 6
# prob(game_even(n), n)
# This takes too much time to compile

In [11]:
def game_odd(n, i):
    # returns the number of non-zero determinant matrices
    # for n is odd
    count = 0 # Counter for the number of non-zero det matrices
    combinations = itertools.combinations(np.arange(n**2), int(np.floor(n**2/2)))
    for comb in combinations:
        mat = np.array([0]*(n**2))
        for k in comb:
            mat[k] = 1
        mat = mat.reshape(n,n)
        if np.linalg.det(mat) != 0:
            count += 1
            # print(mat)
    # print("The number of non-zero determinant matrices is:") 
    return count

In [12]:
game_odd(1,1)

0

In [13]:
game_odd(1,2)

0

In [14]:
game_odd(3,1)

36

In [15]:
game_odd(3,2)

36

In [16]:
# This takes awhile
game_odd(5,1)

2100150

In [17]:
# This also takes awhile 
game_odd(5,2)

2100150

In [18]:
def prob_odd(count, n):
    return count / (math.comb(n**2, int(math.floor((n**2)/2))))

In [19]:
prob_odd(72, 3)

0.5714285714285714

In [20]:
prob_odd(36, 3)

0.2857142857142857

In [21]:
prob_odd(2332344, 5)

0.4485018172028537

In [22]:
prob_odd(2100150, 5)

0.4038517008634117

In [23]:
Mat = np.ones(9)*2
Mat = Mat.reshape(3,3)
Mat[1][1] = 0
print(Mat)

[[2. 2. 2.]
 [2. 0. 2.]
 [2. 2. 2.]]
